<div class="block newsletter" style='text-align: center; margin-left: auto; margin-right: auto;'>
    <div class="title"><strong><?=$block->escapeHtml(__('Newsletter'))?></strong></div>
    <div class="content">
        <form class="form subscribe"
            novalidate
            action="<?=$block->escapeUrl($block->getFormActionUrl())?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail"
            style='display: block'>
            <div class="field newsletter">
                <div class="control">
                    <label for="newsletter">
                        <span class="label">
                            <?=$block->escapeHtml(__('Sign Up for Our Newsletter:'))?>
                        </span>
                        <input name="email" type="email" id="newsletter"
                               placeholder="<?=$block->escapeHtml(__('Email adress'))?>"
                               data-mage-init='{"mage/trim-input":{}}'
                               data-validate="{required:true, 'validate-email':true}"
                               style="width: 200%;"
                        />
                    </label>
                </div>
            </div>
            <div class="actions" style='display: block'>
                <button class="action subscribe primary"
                        title="<?=$block->escapeHtmlAttr(__('Subscribe'))?>"
                        type="submit"
                        aria-label="Subscribe">
                    <span><?=$block->escapeHtml(__('Subscribe'))?></span>
                </button>
            </div>
        </form>
    </div>
</div>
